# failover_config.yml
# WARNING: public file (do not forget everyone read permission in S3) 
---
comunicacion:
  production: XXXXX-comms.herokuapp.com
  failover: XXXXX-comms.aws.ie.a9sapp.eu
energia:
  production: XXXXX-energy.herokuapp.com
  failover: XXXXX-comms.aws.ie.a9sapp.eu
finanzas:
  production: XXXXX-pf.herokuapp.com
  failover: XXXXX-pf.aws.ie.a9sapp.eu
finanzas-agentes:
  production: XXXXX-pf-agents.herokuapp.com
  failover: XXXXX-pf-agents.aws.ie.a9sapp.eu
finanzas-backend:
  production: XXXXX-pf-backend.herokuapp.com
  failover: XXXXX-pf-backend.aws.ie.a9sapp.eu
mi:
  production: XXXXX-cam.herokuapp.com
  failover: XXXXX-cam.aws.ie.a9sapp.eu
seguros:
  production: XXXXX-seguros.herokuapp.com
  failover: XXXXX-seguros.aws.ie.a9sapp.eu
www:
  production: XXXXX-cms.herokuapp.com
  failover: XXXXX-cms.aws.ie.a9sapp.eu
