name             'install_vagrant'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures install_vagrant'
long_description 'Installs/Configures install_vagrant'
version          '0.1.0'
