---
format: json
contacts:
- value: jorge@moratilla.com
  type: 2
  status: 2
  id: 0198901
- value: jorge+nuria@moratilla.com
  type: 2
  status: 2
account_api_key: u198901-e2ba9061264b9701b21732f2
monitors:
- friendlyname: moratilla-web
  id: '776584576'
  url: http://www.moratilla.com
  type: 2
  keywordtype: 2
  keywordvalue: moratilla
  alertcontacts:
  - 0198901
- friendlyname: nuriacbotey-web
  id: '776584577'
  url: http://www.nuriacbotey.es
  type: 2
  keywordtype: 2
  keywordvalue: nuria
  alertcontacts:
  - 2306478
- friendlyname: google-web
  id: '776584578'
  url: http://www.google.es
  type: 2
  keywordtype: 2
  keywordvalue: google
  alertcontacts:
  - 0198901
  - 2306478
